server:
  port: ${PORT:8090}

spring:
  application:
    name: SSCS-COR-Backend
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:11MB}
      max-request-size: ${MAX_FILE_SIZE:11MB}

coh:
  url: ${COH_URL:http://localhost:8081}

notifications:
  url: ${NOTIFICATIONS_API_URL:http://localhost:8082}

idam:
  url: ${IDAM_URL:http://localhost:4501}
  s2s-auth:
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sscs}
    url: ${IDAM_S2S_AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:SSCS_SYSTEM_UPDATE}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:SSCS_SYSTEM_UPDATE}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_SSCS_URL:https://localhost:9000/poc}
core_case_data:
  api:
    url: ${CORE_CASE_DATA_URL:http://localhost:4452}
  caseTypeId: Benefit
  jurisdictionId: SSCS

create_ccd_endpoint: ${CREATE_CCD_ENDPOINT:false}

document_management:
  url: ${DOCUMENT_MANAGEMENT_URL:http://localhost:4603}

pdf:
  api:
    url: ${PDF_API_URL:http://localhost:5500}

appellant:
  appeal:
    html:
      template:
        path: /

preliminary_view:
  html:
    template:
      path: /templates/tribunalsView.html
online_hearing_finished:
  html:
    template:
      path: /templates/onlineHearingSummary.html
question:
  html:
    template:
      path: /templates/questions.html

appeal:
  email:
    host: ${EMAIL_SERVER_HOST:localhost}
    port: ${EMAIL_SERVER_PORT:1025}
    smtp:
      tls:
        enabled: ${EMAIL_SMTP_TLS_ENABLED:true}
    from: ${EMAIL_FROM:sscs@hmcts.net}
    to: ${EMAIL_TO:receiver@hmcts.net}
    subject: ${EMAIL_SUBJECT:Your appeal}
    message: ${EMAIL_MESSAGE:Your appeal has been created \nPlease do not respond to this email}
    dwpEmailAddress: ${DWP_EMAIL:dwp@example.com}

enable_debug_error_message: ${ENABLE_DEBUG_ERROR_MESSAGE:true}enable_select_by_case_id: ${ENABLE_SELECT_BY_CASE_ID:false}