server:
  port: ${PORT:8090}

spring:
  application:
    name: SSCS-COR-Backend

coh:
  url: ${COH_URL:http://localhost:8081}

idam:
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:sscs}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}