java:
  image: 'hmctspublic.azurecr.io/sscs/cor-backend:latest'
  applicationPort: 8080
  aadIdentityName: sscs
  ingressHost: sscs-cor-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
        - idam-sscs-oauth2-client-secret
        - idam-sscs-systemupdate-user
        - idam-sscs-systemupdate-password
        - docmosis-api-key
        - sscs-s2s-secret
  environment:
    SERVER_PORT: 8080
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-cor-backend
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_URL: http://idam-api.aat.platform.hmcts.net
    IDAM_SSCS_URL: https://evidence-sharing-preprod.sscs.reform.hmcts.net
    IDAM_OAUTH2_REDIRECT_URL: https://evidence-sharing-preprod.sscs.reform.hmcts.net
    CREATE_CCD_ENDPOINT: true
    ENABLE_DEBUG_ERROR_MESSAGE: true
    ENABLE_SELECT_BY_CASE_ID: true
    EMAIL_SERVER_HOST: mta.reform.hmcts.net
    EMAIL_SERVER_PORT: 25
    CASEWORKER_EMAIL: joelle.richards@hmcts.net
    DWP_EMAIL: joelle.richards@hmcts.net
    EMAIL_FROM: joelle.richards@hmcts.net
    JUI_BASE_URL: https://jui-webapp-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CORE_CASE_DATA_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    COH_URL: http://coh-cor-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_S2S_AUTH: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PDF_API_URL: http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    NOTIFICATIONS_API_URL: http://sscs-tya-notif-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PDF_SERVICE_CONVERT_URL: https://docmosis-development.platform.hmcts.net/rs/convert
    PDF_SERVICE_HEALTH_URL: https://docmosis-development.platform.hmcts.net/rs/status
    PDF_SERVICE_BASE_URL: https://docmosis-development.platform.hmcts.net/rs/render
    PDF_SERVICE_ACCESS_KEY: ${PDF_SERVICE_ACCESS_KEY}