java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 8080
  environment:
    SERVER_PORT: 8080
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-cor-backend
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
    IDAM_SSCS_SYSTEMUPDATE_USER: ${IDAM_SSCS_SYSTEMUPDATE_USER}
    IDAM_SSCS_SYSTEMUPDATE_PASSWORD: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
    IDAM_OAUTH2_CLIENT_SECRET: ${IDAM_OAUTH2_CLIENT_SECRET}
    IDAM_OAUTH2_REDIRECT_URL: https://sscs-case-loader-sandbox.service.core-compute-sandbox.internal
    IDAM_URL: https://preprod-idamapi.reform.hmcts.net:3511
    IDAM_SSCS_URL: https://evidence-sharing-preprod.sscs.reform.hmcts.net
    CREATE_CCD_ENDPOINT: true
    ENABLE_DEBUG_ERROR_MESSAGE: true
    ENABLE_SELECT_BY_CASE_ID: true
    EMAIL_SERVER_HOST: mta.reform.hmcts.net
    EMAIL_SERVER_PORT: 25
    DWP_EMAIL: var.dwp_email
    APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
ccd:
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  apiGateway:
    s2sKey: ${API_GATEWAY_S2S_KEY}
    idamClientSecret: ${API_GATEWAY_IDAM_SECRET}

  dataStoreApi:
    s2sKey: ${DATA_STORE_S2S_KEY}

  definitionStoreApi:
    s2sKey: ${DEFINITION_STORE_S2S_KEY}

  caseManagementWeb:
    enabled: true


    importer:
      definitions:
      #  - https://raw.githubusercontent.com/hmcts/Probate-CCD-Import-Spreadsheets/master/spreadsheet/back-office/CCD_Probate_V04.32.01-Hlm.xlsx
      # location incorrect.. its not in b-o, do we need this sheet?   - https://raw.githubusercontent.com/hmcts/Probate-CCD-Import-Spreadsheets/master/spreadsheet/back-office/CCD_Probate_Legacy_V00.01-Dev.xlsx
      #      - https://github.com/hmcts/Probate-CCD-Import-Spreadsheets/raw/master/spreadsheet/CCD_Probate_V21.02-Dev.xlsx
      userRoles:
        - caseworker-sscs
        - caseworker-sscs-systemupdate
        - caseworker-sscs-anonymouscitizen
        - citizen
        - caseworker-sscs-callagent
        - caseworker-sscs-judge
        - caseworker-sscs-panelmember