java:
  image: 'https://hmctspublic.azurecr.io/sscs/cor-backend:latest'
  applicationPort: 8080
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
        - idam-sscs-oauth2-client-secret
        - idam-sscs-systemupdate-user
        - idam-sscs-systemupdate-password
        - docmosis-api-key
        - sscs-s2s-secret
  environment:
    SERVER_PORT: 8080
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-cor-backend
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_URL: http://idam-api.aat.platform.hmcts.net
    IDAM_SSCS_URL: https://evidence-sharing-preprod.sscs.reform.hmcts.net
    IDAM_OAUTH2_REDIRECT_URL: https://evidence-sharing-preprod.sscs.reform.hmcts.net
    CREATE_CCD_ENDPOINT: true
    ENABLE_DEBUG_ERROR_MESSAGE: true
    ENABLE_SELECT_BY_CASE_ID: true
    EMAIL_SERVER_HOST: mta.reform.hmcts.net
    EMAIL_SERVER_PORT: 25
    DWP_EMAIL: var.dwp_email
    JUI_BASE_URL: https://jui-webapp-aat.service.core-compute-aat.internal