java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_S2S_AUTH: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    COH_URL: http://coh-cor-aat.service.core-compute-aat.internal
    CORE_CASE_DATA_URL: http://ccd-data-store-api-aat.service.core-compute-aat.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-aat.service.core-compute-aat.internal
    PDF_API_URL: http://cmc-pdf-service-aat.service.core-compute-aat.internal
    NOTIFICATIONS_API_URL: http://sscs-tya-notif-aat.service.core-compute-aat.internal

    IDAM_URL: http://idam-api.aat.platform.hmcts.net
    IDAM_SSCS_URL: https://evidence-sharing-preprod.sscs.reform.hmcts.net
    IDAM_OAUTH2_REDIRECT_URL: https://evidence-sharing-preprod.sscs.reform.hmcts.net
    CREATE_CCD_ENDPOINT: true
    ENABLE_DEBUG_ERROR_MESSAGE: true
    ENABLE_SELECT_BY_CASE_ID: true
    EMAIL_SERVER_HOST: mta.reform.hmcts.net
    EMAIL_SERVER_PORT: 25
    DWP_EMAIL: var.dwp_email
    JUI_BASE_URL: https://jui-webapp-aat.service.core-compute-aat.internal
