capacity = "2"
infrastructure_env = "preprod"
enable_select_by_case_id = "true"
createCcdEndpoint = "true"
jui_base_url = "https://jui-webapp-aat.service.core-compute-aat.internal"
idam_redirect_url = "https://sscs-case-loader-aat.service.core-compute-aat.internal"
appinsights_instrumentation_key = "e2300a5f-a16f-4657-a63b-41913805661e"