infrastructure_env = "preprod"
enable_select_by_case_id = "true"
createCcdEndpoint = "true"
jui_base_url = "https://jui-webapp-demo.service.core-compute-demo.internal"
idam_redirect_url = "https://sscs-case-loader-demo.service.core-compute-demo.internal"
appinsights_instrumentation_key = "07ec19ba-d773-4d1c-8a35-e9a814d61507"