infrastructure_env = "preprod"
enable_select_by_case_id = "true"
createCcdEndpoint = "true"
jui_base_url = "https://jui-webapp-demo.service.core-compute-demo.internal"
idam_redirect_url = "https://sscs-case-loader-demo.service.core-compute-demo.internal"