capacity = "2"
infrastructure_env = "prod"
enable_debug_error_message = "false"
email_from_address = "pipappeals@justice.gov.uk"
jui_base_url = "https://jcm.judiciary.uk"
idam_redirect_url = "https://sscs-case-loader-prod.service.core-compute-prod.internal"
